# AWS CodeBuild spec to build an Elastic Beanstalk artifact for AWS CodePipeline to deploy
version: 0.2
    
phases:
  install:
    runtime-versions:
      dotnet: 3.1
   
  pre_build:
    commands:
      - dotnet restore 
      
  build:
    commands:
      - dotnet build 
      
  post_build:
    commands:
      - dotnet publish -c Release -r linux-x64        
      
artifacts:
  files:
    - '**/*'
  base-directory: 'bin/Release/netcoreapp3.1/linux-x64/publish'